type = "javascript"

name = "mcuni-balances"
account_id = "44321e1b7fbd29b56b65c1890a3bbee2"
compatibility_date = "2022-11-03"

kv_namespaces = [
    { binding = "BALANCES", id = "ec7934e9c0ce45a3b9041eff64321fb0" },
    { binding = "USERNAMES", id = "23d2abdfa9144310998acf53a85f0ebc" }
]

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"
dir = "build"

[triggers]
crons = ["*/30 * * * *"]

[miniflare]
kv_persist = true